import "./globals.css";

import { Code2 } from "lucide-react";
import type { Metadata } from "next";
import Link from "next/link";
import { Header } from "./_components/Header";
import { Providers } from "./_context/providers";
import { Footer } from "./_components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en">
        <body className="flex min-h-screen flex-col">
          <Header />
          <main className="flex-1 p-4">{children}</main>
          <Footer />
        </body>
      </html>
    </Providers>
  );
}
