import "./globals.css";

import type { Metadata } from "next";
import { Providers } from "./_context/providers";
import { Header } from "./_components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          <div className="p-4">{children}</div>
        </Providers>
      </body>
    </html>
  );
}
